<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203064437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE leave (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start DATE NOT NULL, "end" DATE NOT NULL, type VARCHAR(255) NOT NULL, minutes INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE monthly_time_balance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, month VARCHAR(255) NOT NULL, expected_minutes INT NOT NULL, worked_minutes INT NOT NULL, balance_minutes INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE work_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, worked_minutes INT NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_94C7764AA9E377A ON work_logs (date)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE leave');
        $this->addSql('DROP TABLE monthly_time_balance');
        $this->addSql('DROP TABLE work_logs');
    }
}
